//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul  8 14:49:55 2019 by ROOT version 6.16/00)
//      from the StreamerInfo in file /global/projecta/projectdirs/lz/data/MDC2/calibration/LZAP-3.12.0-PHYSICS-3.12.1/AmLi_1336/lz_AmLi_1336000010_0005_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__RQMCTruthPulses_h
#define RQ__RQMCTruthPulses_h
namespace RQ {
class RQMCTruthPulses;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace RQ {
class RQMCTruthPulses : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nRQMCTruthPulses;    //
   vector<unsigned short> pulseIdentifier;     //
   vector<int>            vertexNumber;        //
   vector<unsigned int>   pheCount;            //
   vector<double>         firstPheTime_ns;     //
   vector<double>         lastPheTime_ns;      //
   vector<vector<unsigned short> > pmtIndices;          //
   vector<vector<unsigned int> >   pmtHits;             //

   RQMCTruthPulses();
   RQMCTruthPulses(const RQMCTruthPulses & );
   virtual ~RQMCTruthPulses();

   ClassDef(RQMCTruthPulses,2); // Generated by MakeProject.
};
} // namespace
#endif
