//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul  8 14:49:55 2019 by ROOT version 6.16/00)
//      from the StreamerInfo in file /global/projecta/projectdirs/lz/data/MDC2/calibration/LZAP-3.12.0-PHYSICS-3.12.1/AmLi_1336/lz_AmLi_1336000010_0005_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__EventHeader_h
#define RQ__EventHeader_h
namespace RQ {
class EventHeader;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>

namespace RQ {
class EventHeader : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   unsigned long eventID;     //event ID, taken from globalEvt
   string        rawFileName;    //file that this event belongs to
   unsigned long triggerTimeStamp_s;    //seconds component of trigger time (POSIX)
   unsigned long triggerTimeStamp_ns;    //ns component of trigger time (ns past triggerTimeStamp_s)

   EventHeader();
   EventHeader(const EventHeader & );
   virtual ~EventHeader();

   ClassDef(EventHeader,2); // Generated by MakeProject.
};
} // namespace
#endif
