//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul  8 14:49:55 2019 by ROOT version 6.16/00)
//      from the StreamerInfo in file /global/projecta/projectdirs/lz/data/MDC2/calibration/LZAP-3.12.0-PHYSICS-3.12.1/AmLi_1336/lz_AmLi_1336000010_0005_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__PileUpScatters_h
#define RQ__PileUpScatters_h
namespace RQ {
class PileUpScatters;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
namespace std {} using namespace std;
namespace std {} using namespace std;

namespace RQ {
class PileUpScatters : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nPileUpScatters;    //Number of pile up interactions found in this event
   vector<int> nS1;                //Number of S1s in pile up interaction
   vector<vector<int> > s1PulseIDs;         //IDs of S1 pulses
   vector<int>          nS2;                //Number of S2s in pile up interaction
   vector<vector<int> > s2PulseIDs;         //IDs of S2 pulses

   PileUpScatters();
   PileUpScatters(const PileUpScatters & );
   virtual ~PileUpScatters();

   ClassDef(PileUpScatters,2); // Generated by MakeProject.
};
} // namespace
#endif
