//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Mon Jul  8 14:49:55 2019 by ROOT version 6.16/00)
//      from the StreamerInfo in file /global/projecta/projectdirs/lz/data/MDC2/calibration/LZAP-3.12.0-PHYSICS-3.12.1/AmLi_1336/lz_AmLi_1336000010_0005_lzap.root
//////////////////////////////////////////////////////////


#ifndef RQ__RQMCDarkCounts_h
#define RQ__RQMCDarkCounts_h
namespace RQ {
class RQMCDarkCounts;
} // end of namespace.

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>

namespace RQ {
class RQMCDarkCounts : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         nRQMCDarkCounts;    //
   vector<unsigned short> pmtIndex;           //
   vector<double>         time_ns;            //

   RQMCDarkCounts();
   RQMCDarkCounts(const RQMCDarkCounts & );
   virtual ~RQMCDarkCounts();

   ClassDef(RQMCDarkCounts,2); // Generated by MakeProject.
};
} // namespace
#endif
